### ISSUE TITLE
percent to a time value 

### ISSUE THREAD

**Issue by DLParkin** [dmitrymorozoff/react-dashed-progress#1]
I really like this progress bar, it is great. How could I change the value to display as a timer instead?

**Comment by dmitrymorozoff** [comment]
@floppyspace Hey. To make a timer out of this component, you need to set the timer state and change the state value in the setInterval function. And in the component parameter, pass this timer value in the value prop.

**Comment by dmitrymorozoff** [comment]
@floppyspace  [This article](https://medium.com/@650egor/react-30-day-challenge-day-1-simple-timer-df85d0867553) describes how to make a timer.  

In the render method, I need to transfer the current state of the timer to my component.

`<DashedProgress value={this.state.timer}/>`

**Comment by DLParkin** [comment]
@dmitrymorozoff  Many thanks for the reply and this great progress bar. 

I ended up overlaying a timer and calculated the percentage so it displayed as intended.

Great work and appreciate the time you put into making this.
